//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooLogicSA.Promociones.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZooLogicSA.Promociones.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Comprobante&gt;
        ///  &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;0&quot; /&gt;
        ///  &lt;Fecha TipoDato=&quot;D&quot; Valor=&quot;12/07/2012&quot; /&gt;
        ///  &lt;Cliente&gt;
        ///    &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;00002&quot; /&gt;
        ///    &lt;Provincia&gt;
        ///      &lt;Codigo TipoDato=&quot;N&quot; Valor=&quot;1&quot; /&gt;
        ///      &lt;Descripcion TipoDato=&quot;C&quot; Valor=&quot;Prov&quot; /&gt;
        ///    &lt;/Provincia&gt;
        ///  &lt;/Cliente&gt;
        ///  &lt;Facturadetalle&gt;
        ///    &lt;Item&gt;
        ///      &lt;IdItemArticulos TipoDato=&quot;C&quot; Valor=&quot;0&quot; /&gt;
        ///      &lt;Articulo&gt;
        ///        &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;ART21&quot; /&gt;
        ///        &lt;Familia TipoDato=&quot;C&quot; Va [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobanteBasicoPruebas {
            get {
                return ResourceManager.GetString("ComprobanteBasicoPruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;COMPROBANTE&gt;&lt;CLIENTE&gt;&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;0000000001&quot; /&gt;&lt;FECHANACIMIENTO TipoDato=&quot;D&quot; Valor=&quot;01/01/2001&quot; /&gt;&lt;LOCALIDAD TipoDato=&quot;C&quot; Valor=&quot;C.A.B.A.&quot; /&gt;&lt;NOMBRE TipoDato=&quot;C&quot; Valor=&quot;Martín Gomez&quot; /&gt;&lt;PAIS&gt;&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;AR&quot; /&gt;&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;Argentina&quot; /&gt;&lt;/PAIS&gt;&lt;PROVINCIA&gt;&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;00&quot; /&gt;&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;C.A.B.A.&quot; /&gt;&lt;/PROVINCIA&gt;&lt;CLASIFICACION&gt;&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;MINORISTA&quot; /&gt;&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;&lt;/CLASIFICACION&gt;&lt;ESTAD [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobanteBUG6323 {
            get {
                return ResourceManager.GetString("ComprobanteBUG6323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Comprobante&gt;
        ///    &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;guidFactura&quot; /&gt;
        ///    &lt;Sucursal&gt;
        ///      &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;SUCUTEST&quot; /&gt;
        ///      &lt;Segmentacion&gt;
        ///         &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;SEGMENTA&quot; /&gt;
        ///      &lt;/Segmentacion&gt;
        ///    &lt;/Sucursal&gt;
        ///    &lt;Cliente&gt;
        ///    &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;0000000001&quot; /&gt;
        ///    &lt;Fechanacimiento TipoDato=&quot;D&quot; Valor=&quot;01/01/01&quot; /&gt;
        ///    &lt;Localidad TipoDato=&quot;C&quot; Valor=&quot;C.A.B.A.&quot; /&gt;
        ///    &lt;Nombre TipoDato=&quot;C&quot; Valor=&quot;Martín Gomez&quot; /&gt;
        ///    &lt;Pais&gt;
        ///      &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;AR&quot; /&gt;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobanteCompleto {
            get {
                return ResourceManager.GetString("ComprobanteCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Comprobante&gt;
        ///  &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;0&quot; /&gt;
        ///  &lt;Fecha TipoDato=&quot;D&quot; Valor=&quot;12/07/2012&quot; /&gt;
        ///  &lt;Cliente&gt;
        ///    &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;00002&quot; /&gt;
        ///    &lt;Provincia&gt;
        ///      &lt;Codigo TipoDato=&quot;N&quot; Valor=&quot;1&quot; /&gt;
        ///      &lt;Descripcion TipoDato=&quot;C&quot; Valor=&quot;Prov&quot; /&gt;
        ///    &lt;/Provincia&gt;
        ///  &lt;/Cliente&gt;
        ///  &lt;Facturadetalle&gt;
        ///    &lt;Item&gt;
        ///      &lt;IdItemArticulos TipoDato=&quot;C&quot; Valor=&quot;0&quot; /&gt;
        ///      &lt;Articulo&gt;
        ///        &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;LED403D&quot; /&gt;
        ///        &lt;Familia TipoDato=&quot;C&quot;  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobanteConValor {
            get {
                return ResourceManager.GetString("ComprobanteConValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;COMPROBANTE&gt;
        ///	&lt;CLIENTE&gt;
        ///		&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;FECHANACIMIENTO TipoDato=&quot;D&quot; Valor=&quot;01/01/1900&quot; /&gt;
        ///		&lt;LOCALIDAD TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;NOMBRE TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;PAIS&gt;
        ///			&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///			&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;/PAIS&gt;
        ///		&lt;PROVINCIA&gt;
        ///			&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///			&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;/PROVINCIA&gt;
        ///		&lt;CLASIFICACION&gt;
        ///			&lt;CODIGO TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///			&lt;DESCRIPCION TipoDato=&quot;C&quot; Valor=&quot;&quot; /&gt;
        ///		&lt;/CLASIFICACION&gt;
        ///		&lt;ESTADO [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobanteListaDePrecios {
            get {
                return ResourceManager.GetString("ComprobanteListaDePrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Comprobante&gt;
        ///  &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;0&quot; /&gt;
        ///  &lt;Cliente&gt;
        ///    &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;0000000001&quot; /&gt;
        ///    &lt;Fechanacimiento TipoDato=&quot;D&quot; Valor=&quot;01/01/01&quot; /&gt;
        ///    &lt;Localidad TipoDato=&quot;C&quot; Valor=&quot;C.A.B.A.&quot; /&gt;
        ///    &lt;Nombre TipoDato=&quot;C&quot; Valor=&quot;Martín Gomez&quot; /&gt;
        ///    &lt;Pais&gt;
        ///      &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;AR&quot; /&gt;
        ///      &lt;Descripcion TipoDato=&quot;C&quot; Valor=&quot;Argentina&quot; /&gt;
        ///    &lt;/Pais&gt;
        ///    &lt;Provincia&gt;
        ///      &lt;Codigo TipoDato=&quot;C&quot; Valor=&quot;00&quot; /&gt;
        ///      &lt;Descripcion TipoDato=&quot;C&quot; Valor=&quot;C.A.B.A.&quot; /&gt;
        ///    &lt;/Provin [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ComprobantePoli {
            get {
                return ResourceManager.GetString("ComprobantePoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version = &quot;1.0&quot; encoding=&quot;Windows-1252&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;VFPData&gt;
        ///	&lt;cprecioartic&gt;
        ///		&lt;articulo&gt;A1&lt;/articulo&gt;
        ///		&lt;color/&gt;
        ///		&lt;talle/&gt;
        ///		&lt;lista&gt;LISTA3&lt;/lista&gt;
        ///		&lt;monedalista&gt;PESOS&lt;/monedalista&gt;
        ///		&lt;precio&gt;80.00&lt;/precio&gt;
        ///	&lt;/cprecioartic&gt;
        ///	&lt;cprecioartic&gt;
        ///		&lt;articulo&gt;A2&lt;/articulo&gt;
        ///		&lt;color/&gt;
        ///		&lt;talle/&gt;
        ///		&lt;lista&gt;LISTA3&lt;/lista&gt;
        ///		&lt;monedalista&gt;PESOS&lt;/monedalista&gt;
        ///		&lt;precio&gt;150.00&lt;/precio&gt;
        ///	&lt;/cprecioartic&gt;
        ///	&lt;cprecioartic&gt;
        ///		&lt;articulo&gt;A3&lt;/articulo&gt;
        ///		&lt;color/&gt;
        ///		&lt;talle/&gt;
        ///		&lt;lista&gt;LISTA3&lt;/lis [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PreciosAdicionales {
            get {
                return ResourceManager.GetString("PreciosAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;VFPData xml:space=&quot;preserve&quot;&gt;
        ///	&lt;xsd:schema id=&quot;VFPData&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///		&lt;xsd:element name=&quot;VFPData&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        ///			&lt;xsd:complexType&gt;
        ///				&lt;xsd:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///					&lt;xsd:element name=&quot;row&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///						&lt;xsd:complexType&gt;
        ///							&lt;xsd:attribute name=&quot;codigo&quot; use=&quot;optional&quot;&gt;
        ///								&lt;xsd:simpleType&gt;
        ///		 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLdeFox {
            get {
                return ResourceManager.GetString("XMLdeFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Promocion xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;EleccionParticipante&gt;None&lt;/EleccionParticipante&gt;
        ///&lt;Beneficios&gt;
        ///  &lt;Beneficio&gt;
        ///	&lt;Cuantos&gt;1&lt;/Cuantos&gt;
        ///	&lt;Cambio&gt;CambiarValor&lt;/Cambio&gt;
        ///	&lt;ParticipanteRegla&gt;2&lt;/ParticipanteRegla&gt;
        ///	&lt;Atributo&gt;Descuento&lt;/Atributo&gt;
        ///	&lt;Valor xsi:type=&quot;xsd:string&quot;&gt;30&lt;/Valor&gt;
        ///  &lt;/Beneficio&gt;
        ///&lt;/Beneficios&gt;
        ///&lt;Participantes&gt;
        ///  &lt;ParticipanteRegla&gt;
        ///	&lt;Id&gt;1&lt;/Id&gt;
        ///	&lt;Codigo&gt;Comprobante&lt;/ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLDeUnaPromocion {
            get {
                return ResourceManager.GetString("XMLDeUnaPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;DatosParticipante&gt;
        ///  &lt;Participante Entidad=&quot;CLIENTE&quot;&gt;
        ///    &lt;Registro&gt;
        ///      &lt;Atributo Nombre=&quot;CODIGO&quot; Valor=&quot;1&quot; /&gt;
        ///      &lt;Atributo Nombre=&quot;NOMBRE&quot; Valor=&quot;Juan Perez&quot; /&gt;
        ///      &lt;Atributo Nombre=&quot;LOCALIDAD&quot; Valor=&quot;CABA&quot; /&gt;
        ///      &lt;Atributo Nombre=&quot;FECHANACIMIENTO&quot; Valor=&quot;01/01/1980&quot; /&gt;
        ///            &lt;/Registro&gt;
        ///            &lt;Registro&gt;
        ///      &lt;Atributo Nombre=&quot;CODIGO&quot; Valor=&quot;1&quot; /&gt;
        ///      &lt;Atributo Nombre=&quot;NOMBRE&quot; Valor=&quot;Juan Perez&quot; /&gt;
        ///      &lt;Atributo Nombre=&quot;LOCALIDAD&quot; Valor=&quot;CABA&quot; /&gt;
        ///      &lt;Atributo Nomb [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLPruebaDatosParticipante {
            get {
                return ResourceManager.GetString("XMLPruebaDatosParticipante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Participantes&gt;
        ///
        /// &lt;Participante Entidad=&quot;CLIENTE&quot; Descripcion=&quot;zCliente&quot; Detalle=&quot;&quot; Atributo=&quot;aCLIENTE&quot;&gt;
        ///  &lt;Atributos&gt;
        ///   &lt;Atributo Nombre=&quot;CODIGO&quot; Descripcion=&quot;zCódigo&quot; Entidad=&quot;&quot; Atributo=&quot;aCODIGO&quot;/&gt;
        ///   &lt;Atributo Nombre=&quot;NOMBRE&quot; Descripcion=&quot;zNombre&quot; Atributo=&quot;aNOMBRE&quot;/&gt;
        ///   &lt;Participante Entidad=&quot;CLASIFICACION&quot; Descripcion=&quot;zClasificación de cliente&quot; Atributo=&quot;aCLASIFICACION&quot;&gt;
        ///    &lt;Atributos&gt;
        ///     &lt;Atributo Nombre=&quot;CODIGO&quot; Descripcion=&quot;zCódigo&quot; Atributo=&quot;a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLPruebaParticipanteFiltro {
            get {
                return ResourceManager.GetString("XMLPruebaParticipanteFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfPromocion xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Promocion&gt;
        ///    &lt;Participantes&gt;
        ///      &lt;ParticipanteRegla&gt;
        ///        &lt;Id&gt;1&lt;/Id&gt;
        ///        &lt;Codigo&gt;Comprobante&lt;/Codigo&gt;
        ///        &lt;Reglas&gt;
        ///          &lt;Regla&gt;
        ///            &lt;Id&gt;1&lt;/Id&gt;
        ///            &lt;Comparacion&gt;DebeSerIgualA&lt;/Comparacion&gt;
        ///            &lt;Valor xsi:type=&quot;xsd:dateTime&quot;&gt;2012-07-12T00:00:00&lt;/Valor&gt;
        ///            &lt;Atributo&gt;Fecha&lt;/Atributo&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLPruebaPromocion {
            get {
                return ResourceManager.GetString("XMLPruebaPromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Promocion xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Visualizacion&gt;Normal&lt;/Visualizacion&gt;
        ///  &lt;TopeBeneficio&gt;0.00&lt;/TopeBeneficio&gt;
        ///  &lt;EleccionParticipante&gt;None&lt;/EleccionParticipante&gt;
        ///  &lt;Beneficios&gt;
        ///    &lt;Beneficio&gt;
        ///      &lt;Cambio&gt;CambiarValor&lt;/Cambio&gt;
        ///      &lt;Atributo&gt;MONTOFINAL&lt;/Atributo&gt;
        ///      &lt;Valor xsi:type=&quot;xsd:string&quot;&gt;99.00&lt;/Valor&gt;
        ///      &lt;Id&gt;bd49e7b4180942a588f2a5151744b292&lt;/Id&gt;
        ///      &lt;Destinos&gt;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XMLTestBUG6323_Promocion {
            get {
                return ResourceManager.GetString("XMLTestBUG6323_Promocion", resourceCulture);
            }
        }
    }
}
